;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   ter mai 7 2019
; Processor: PIC16F873
; Compiler:  MPASM (Proteus)
;====================================================================

;====================================================================
; DEFINITIONS
;====================================================================

#include p16f873.inc                ; Include register definition file

;====================================================================
; VARIABLES
;====================================================================

;====================================================================
; RESET and INTERRUPT VECTORS
;====================================================================

      ; Reset Vector
RST   code  0x0 
      goto  Start

;====================================================================
; CODE SEGMENT
;====================================================================

PGM   code
Start   

;===========CONFIGURANDO AS PORTAS DE ENTRADA E SAIDA============

;PORTA  PORTAS DE OUTPUT

;; BANK 1
BANKSEL TRISA	   
MOVLW b'00000000' 			; definindo a PORTA  COMO OUTPUT
MOVWF TRISA	 			; enviando o valor para a  PORTA

;PORTB COMO INPUT
MOVLW b'11111111' 			; setando os bits para TRISB
MOVWF TRISB	  			;definindo porta como Input 
;====================================================================

ANALIZA
;;BANK 0
      BANKSEL PORTA
      BTFSS  PORTB,RB1     		; RB1 = 1 ?
      goto DESLIGA_BOMBA	 	; NÃO: continua analisar RB1
      goto LIGA_BOMBA      		; SIM : liga bomba de agua
      
;====================================================================






;;============ROTINA PARA LIGAR A BOMBA DE AGUA===================
LIGA_BOMBA
      BSF PORTA,RA0  			;RA =1  ligando a bomba de agua

goto ANALIZA
;====================================================================

;;============ROTINA PARA DESLIGAR A BOMBA DE AGUA================
;; A bomba de agua será desligada quando o sensor apontar que  a terra está molhada
DESLIGA_BOMBA
      BCF PORTA,RA0  			;RA =1  desliga a bomba de agua

goto ANALIZA
;====================================================================
      END
